python src/main.py \
        --num_trials 5 \
        --num_envs 30 \
        --run_name "scworld_qwen3.6-flash_20_steps" \
        --model "qwen/qwen3.6-flash"  \
        --agent "cdmem"   \
        --env "scienceworld" \
        --start_trial_num 4 \
        --max_steps 20 \
        --is_resume \
        --resume_dir logs/scworld_qwen3.6-flash_20_steps_0511_160223